[project]
name = "OTS-Debugger-Plugin"
description = "CoT viewer and debugger"
authors = [{name = "MMolineux"}]
readme = "README.md"
license = "GPL-3.0-or-later"
dynamic = ["entry-points", "version"]

[project.urls]
Repository = "https://github.com/MMolineux/OTS-Debugger-Plugin"
Documentation = "https://github.com/MMolineux/OTS-Debugger-Plugin/wiki"

[tool.poetry]
include = [{path = "ots_debugger_plugin/ui/dist/**/*", format = ["sdist", "wheel"]}]
version = "0.0.0"

[tool.poetry.dependencies]
opentakserver = ">=1.5.0"
python = ">=3.10, <3.14"

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
style = "semver"
dirty = false
pattern = "((?P<epoch>\\d+)!)?(?P<base>\\d+(\\.\\d+)*)"

[tool.poetry-dynamic-versioning.files."ots_debugger_plugin/__init__.py"]
persistent-substitution = true
initial-content = """
  # These version placeholders will be replaced later during substitution.
  __version__ = "0.0.0"
  __version_tuple__ = (0, 0, 0)
"""

[build-system]
requires = ["poetry-core>=2.0.0", "poetry-dynamic-versioning>=1.0.0,<2.0.0", "setuptools"]
build-backend = "poetry_dynamic_versioning.backend"

[project.entry-points.'opentakserver.plugin']
ots_debugger_plugin = 'ots_debugger_plugin.app:DebuggerPlugin'